### ISSUE TITLE
Issue: Videos pause at random intervals and pause on scroll

### ISSUE THREAD

**Issue by truffl** [insin/tweak-new-twitter#62] opened 2021-08-18 20:15 UTC
On Opera v76.0.4017.208
Scrolling up or down will pause any playing video or gif (I have autoplay off)
Videos will also pause at intervals of 5-15 seconds while playing for some reason?
Disabling Tweak New Twitter returns video playback to normal

**Comment by insin** [comment] 2021-08-19 04:24
Duplicate of #33, Twitter doesn't like it when you change the DOM while a video is playing

**Closed by insin** 2021-08-19 04:24 UTC
