### ISSUE TITLE
Feature Request: Split tweets & retweets timeline on a user page.

### ISSUE THREAD

**Issue by Olshansk** [insin/tweak-new-twitter#73] opened 2021-10-11 15:53 UTC
Similar to how the main timeline is split into a tweets and retweets sections, do you think it'd be possible to do the same thing for user profiles?

I wanted to check if this is not a configuration I had missed or already being worked on. Happy to contribute myself after hearing your thoughts!

**Comment by Arkadeion** [comment] 2022-08-22 18:34
I wanted to submit this myself, but I found this while looking through the open issues. This would be really useful indeed! Sometimes it's hard to actually find a person's tweets among the ton of stuff they retweet, and a function like this would help a lot!

**Comment by insin** [comment] 2022-11-13 11:47
Closing as a duplicate of #13 - the main issue with doing this is the amount of work required to keep your fake "Retweets" timeline working when the user does other things on the page which change the title. That was really painful to get right for the main timeline, which is the only thing which stops me starting this

**Closed by insin** 2022-11-13 11:47 UTC
