### ISSUE TITLE
Liked tweets stays hidden even when set to do nothing

### ISSUE THREAD

**Issue by Winthiefow** [insin/tweak-new-twitter#150] opened 2022-11-10 13:33 UTC
I have not been able to see any liked tweet by people I follow.
I have changed the option of few days ago already so it shouldn't be a refresh issue I suppose.
Maybe a conflict with another option set to "Hide" ?

If it's an expected conflict and not a bug, might I suggest an UI indication of it's existence ?

**Comment by insin** [comment] 2022-11-13 09:12
I can't reproduce this on the main timeline, but is this happening when you click a tweet to view replies to it, then the tweet itself is hidden?

Just found the cause of that and it will be fixed in the next release.

**Comment by Winthiefow** [comment] 2022-11-15 18:14
Switching to Home timeline seems to help my case, I just know I used to see liked tweets in the "Latest tweets" timeline.
I guess using the Home timeline with tweak new twitter is now more bearable so I'll do that for now !

**Closed** 2022-11-15 18:50 UTC
Labels: bug
