### ISSUE TITLE
Disabling reply downvote button

### ISSUE THREAD

**Issue by revolutionchao** [insin/tweak-new-twitter#104] opened 2022-03-25 16:37 UTC
Request: an option to disable the downvote button on replies, or just moving them to a different location as I don't use them, and the placement being in the same place the like button is on normal tweets means downvoting replies I meant to like on accident very frequently.

**Comment by insin** [comment] 2022-03-27 03:45
If you enable "Hide share button under tweets" and "Hide analytics links under your own tweets" it currently accidentally hides downvotes too.

I might just simplify those options into one which hides everything except reply/retweet/like under tweets.

**Comment by GreenDotBlue99** [comment] 2022-05-05 17:39
I personally like that many of the features and buttons in UI would be visible without clicking open menus. At least from the profile interactions ... menu.

**Comment by insin** [comment] 2022-11-13 12:10
Dupe of #94

**Closed by insin** 2022-11-13 12:10 UTC
