### ISSUE TITLE
Adding the home feed behavior for lists

### ISSUE THREAD

**Issue by adhamfarrag** [insin/tweak-new-twitter#178] opened 2023-01-04 00:13 UTC
Hello, not sure if we can ask for features here or not. But can we have the same behavior in home feeds for lists ? Thanks.

**Comment by insin** [comment] 2023-01-16 11:57
Closing as a duplicate of #46

You can accidentally have this now that lists can be pinned to the home timeline - retweets will be filtered out and using the "Retweets" tab switched to retweets only for the last tab you viewed

**Closed by insin** 2023-01-16 11:57 UTC
