### ISSUE TITLE
"hide analytics link" option is currently hiding the share button. 

### ISSUE THREAD

**Issue by lazydaizy** [insin/tweak-new-twitter#167] opened 2022-12-22 19:51 UTC
i assume this is not correct behaviour, and the share button def used to be visible with that setting on. this coincided with twitter shoving the analytics button to the first spot of your own tweets' interaction/metrics bar 

edit to add: the hide metrics options are also borked by this update, and i hope to high heaven that we will be able to hide the new view count metric with that option when it's updated lol.

**Comment by sawayoshisy** [comment] 2022-12-23 01:13
Added info: it seems the "hide share button" option now hides the like button, which makes it feel as if it's an off-by-one caused by the recent update.

**Comment by insin** [comment] 2022-12-23 09:56
Fixed in v2.20.0, no idea now long it'll take the extension stores to review and publish the new version over Christmas though.

**Closed by insin** 2022-12-23 09:56 UTC
